exports.COSTUMES_POUR_PETITS = [
  "Académiques Côtes Combinaisons",
  "Combishorts",
  "Ensembles Jupes",
  "Ensembles Pantalons",
  "Hauts",
  "Jupes",
  "Justaucorps",
  "Pantalons Shorts",
  "Robes",
  "Tuniques",
  "Tutus",
  "Vestes Gilets Cirés",
];

exports.COSTUMES_POUR_MOYENS = [
  "Académiques Côtes Combinaisons",
  "Combishorts",
  "Ensembles Jupes",
  "Ensembles Pantalons",
  "Hauts",
  "Jupes Courtes",
  "Jupes Lngues",
  "Justaucorps",
  "Pantalons",
  "Robes Courtes",
  "Robes Longues",
  "Tuniques",
  "Tutus",
  "Vestes,Gilets",
];

exports.COSTUMES_POUR_GRANDS = [
  "Académiques Côtes Combinaisons",
  "Combishorts",
  "Ensembles Jupes",
  "Ensembles Pantalons",
  "Hauts",
  "Jupes Courtes",
  "Jupes Lngues",
  "Justaucorps",
  "Pantalons",
  "Robes Courtes",
  "Robes Longues",
  "Tuniques",
  "Tutus",
  "Vestes, Gilets, Manteaux",
  "Redingotes",
];

exports.ACCESSOIRES_LIST = [
  "Redingotes",
  "Visage",
  "Haut du corps",
  "Gants",
  "Bas",
  "Corps",
  "Bijoux",
  "Décoration",
  "Parapluies",
];