exports.PAGINATION_LIMIT = 40;
exports.PAGINATION_LIMIT_ADMIN = 20;
exports.ACTIF = 1;
exports.TVA = 0.2;
exports.PROFIL_ADMIN = 1;

exports.DEVIS = 1;
exports.FACTURE = 2;
exports.BON_DE_LIVRAISON = 3;
exports.BON_DE_FACTURATION = 4;
exports.BON_ESSAYAGE = 5;
exports.TYPE_PROMO_POURCENTAGE = 1;
exports.TYPE_PROMO_VALEUR = 2;
exports.STATUT_COMMANDE_FINALISATION_DEVIS = 1;
exports.STATUT_COMMANDE_FINALISATION_DEVIS = 1;
exports.DEFAULT_ADMIN_USER_ID = 1;