const express = require("express");
const router = express.Router();
const loginRouter = require("./admin.connexion");
const devisRouter = require("./admin.devis");
const produitsRouter = require("./admin.produits");
const categoriesRouter = require("./admin.categories");
const fraisPortRouter = require("./admin.fraisport");
const dashboardRouter = require("./admin.dashboard");
const adminIsAuth = require("../../middleware/admin/admin.auth");
const adminLayout = require("../../middleware/admin/admin.layout");
const panierRouter = require("./admin.panier");
const taillesRouter = require("./admin.taille");
const couleurRouter = require("./admin.couleurs");
const factureRouter = require("./admin.facture");
const adresseRouter = require("./admin.adresse");
const clientRouter = require("./admin.client");
const promoRouter = require("./admin.promo");
const applyRouter = require("./admin.apply");

router.use("/login", loginRouter);
router.use("/devis", [adminLayout], devisRouter);
router.use("/produits", [adminLayout], produitsRouter);
router.use("/dashboard", [adminLayout], dashboardRouter);
router.use("/paniers", [adminLayout], panierRouter);
router.use("/categories", [adminLayout], categoriesRouter);
router.use("/dashboard", [adminLayout], dashboardRouter);
router.use("/tailles/", [adminLayout], taillesRouter);
router.use("/couleurs/", [adminLayout], couleurRouter);
router.use("/type-categories", [adminLayout], categoriesRouter);
router.use("/frais-port", [adminLayout], fraisPortRouter);
router.use("/factures", [adminLayout], factureRouter);
router.use("/adresse", [adminLayout], adresseRouter);
router.use("/clients", [adminLayout], clientRouter);
router.use("/promo", [adminLayout], promoRouter);
router.use("/apply", [adminLayout], applyRouter);
module.exports = router;
